doctrine:
    orm:
        entity_managers:
            default:
                dql:
                    string_functions:
                        MATCH_AGAINST: Cirici\MatchAgainstBundle\Extension\Doctrine\MatchAgainst
