parameters:
    cirici_match_against.text_manager.class: Cirici\MatchAgainstBundle\Model\TextSearchManager

services:
    cirici_match_against.text_manager:
        class: %cirici_match_against.text_manager.class%
        calls:
            - [ setEm, ['@doctrine.orm.entity_manager'] ]
