parameters:
#    cirici_match_against.example.class: Cirici\MatchAgainstBundle\Example

services:
#    cirici_match_against.example:
#        class: %cirici_match_against.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
